//
//  Resolver.swift
//  Generated by dikitgen.
//

extension AppResolver {

    func resolveAppResolver() -> AppResolver {
        return provideResolver()
    }

    func resolveAPIClient() -> APIClient {
        return provideAPIClient()
    }

    func resolveDetailViewController(index: Int) -> DetailViewController {
        let apiClient = resolveAPIClient()
        return DetailViewController(dependency: .init(index: index, apiClient: apiClient))
    }

    func resolveListViewController() -> ListViewController {
        let apiClient = resolveAPIClient()
        let appResolver = resolveAppResolver()
        return ListViewController(dependency: .init(apiClient: apiClient, resolver: appResolver))
    }

}

