//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Foundation
import UIKit

extension AppResolver {

    func resolveAppResolver() -> AppResolver {
        return provideResolver()
    }

    func resolveDetailViewController(value: Int) -> DetailViewController {
        let multiplier = resolveMultiplier(value: value)
        return DetailViewController.makeInstance(dependency: .init(multiplier: multiplier))
    }

    func resolveListViewController() -> ListViewController {
        let appResolver = resolveAppResolver()
        return ListViewController.makeInstance(dependency: .init(resolver: appResolver))
    }

    func resolveMultiplier(value: Int) -> Multiplier {
        return Multiplier(dependency: .init(value: value))
    }

}

